/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.idcardgenerator;

import com.github.lgooddatepicker.components.DatePickerSettings;
import javax.swing.JOptionPane;
import java.sql.*;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Random;
/**
 *
 * @author Prashant PC
 */
public class DetailsForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public DetailsForm() {
        initComponents();
       
        //datepicker ui changes
        DatePickerSettings datePickerSettings = new DatePickerSettings();
        datePickerSettings.setAllowKeyboardEditing(false);
        
        datePicker1.setSettings(datePickerSettings);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background_Panel = new javax.swing.JPanel();
        parent_Panel = new javax.swing.JPanel();
        Submit_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        _firstName = new javax.swing.JTextField();
        _lastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        _email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        _city = new javax.swing.JTextField();
        _phoneNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        _firstNameError = new javax.swing.JLabel();
        _lastNameError = new javax.swing.JLabel();
        _emailError = new javax.swing.JLabel();
        _cityError = new javax.swing.JLabel();
        _stateError = new javax.swing.JLabel();
        _phoneError = new javax.swing.JLabel();
        _bloodGrouplist = new javax.swing.JComboBox<>();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        _program = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background_Panel.setBackground(new java.awt.Color(51, 153, 255));
        background_Panel.setForeground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout background_PanelLayout = new javax.swing.GroupLayout(background_Panel);
        background_Panel.setLayout(background_PanelLayout);
        background_PanelLayout.setHorizontalGroup(
            background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );
        background_PanelLayout.setVerticalGroup(
            background_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 895, Short.MAX_VALUE)
        );

        getContentPane().add(background_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 895));

        parent_Panel.setBackground(new java.awt.Color(255, 255, 255));

        Submit_btn.setText("SUBMIT");
        Submit_btn.setBackground(new java.awt.Color(0, 153, 255));
        Submit_btn.setFont(new java.awt.Font("Open Sans SemiBold", 1, 24)); // NOI18N
        Submit_btn.setForeground(new java.awt.Color(255, 255, 255));
        Submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Please Enter Your Details");
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N

        jLabel2.setText("First name");
        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));

        _firstName.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        _firstName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _firstName.setAlignmentX(2.0F);
        _firstName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        _firstName.setCaretColor(new java.awt.Color(153, 153, 153));
        _firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _firstNameActionPerformed(evt);
            }
        });

        _lastName.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        _lastName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _lastName.setAlignmentX(2.0F);
        _lastName.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        _lastName.setCaretColor(new java.awt.Color(153, 153, 153));
        _lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _lastNameActionPerformed(evt);
            }
        });

        jLabel4.setText("Last name");
        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));

        jLabel3.setText("Email");
        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));

        _email.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        _email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _email.setAlignmentX(2.0F);
        _email.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        _email.setCaretColor(new java.awt.Color(153, 153, 153));
        _email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _emailActionPerformed(evt);
            }
        });

        jLabel5.setText("City");
        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));

        _city.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        _city.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _city.setAlignmentX(2.0F);
        _city.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        _city.setCaretColor(new java.awt.Color(153, 153, 153));
        _city.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _cityActionPerformed(evt);
            }
        });

        _phoneNumber.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        _phoneNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _phoneNumber.setAlignmentX(2.0F);
        _phoneNumber.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true), javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1)));
        _phoneNumber.setCaretColor(new java.awt.Color(153, 153, 153));
        _phoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _phoneNumberActionPerformed(evt);
            }
        });

        jLabel6.setText("Phone number");
        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));

        jLabel7.setText("Program");
        jLabel7.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));

        jLabel8.setText("Date of birth");
        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));

        jLabel9.setText("Blood group");
        jLabel9.setFont(new java.awt.Font("Open Sans", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 153, 153));

        _firstNameError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _firstNameError.setForeground(new java.awt.Color(255, 102, 102));

        _lastNameError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _lastNameError.setForeground(new java.awt.Color(255, 102, 102));

        _emailError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _emailError.setForeground(new java.awt.Color(255, 102, 102));

        _cityError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _cityError.setForeground(new java.awt.Color(255, 102, 102));

        _stateError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _stateError.setForeground(new java.awt.Color(255, 102, 102));

        _phoneError.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        _phoneError.setForeground(new java.awt.Color(255, 102, 102));

        _bloodGrouplist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A⁺", "A⁻", "B⁺", "B⁻", "AB⁺", "AB⁻", "O⁺", "O⁻" }));
        _bloodGrouplist.setFont(new java.awt.Font("Open Sans SemiBold", 1, 14)); // NOI18N

        datePicker1.setFont(new java.awt.Font("Open Sans SemiBold", 0, 14)); // NOI18N

        _program.setFont(new java.awt.Font("Open Sans SemiBold", 0, 14)); // NOI18N
        _program.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BIT", "BCA", "CIVIL", "MANAGEMENT" }));
        _program.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _programActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout parent_PanelLayout = new javax.swing.GroupLayout(parent_Panel);
        parent_Panel.setLayout(parent_PanelLayout);
        parent_PanelLayout.setHorizontalGroup(
            parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parent_PanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(parent_PanelLayout.createSequentialGroup()
                        .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(parent_PanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1))
                            .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(parent_PanelLayout.createSequentialGroup()
                                    .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                    .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parent_PanelLayout.createSequentialGroup()
                                            .addComponent(_lastNameError)
                                            .addGap(344, 344, 344))
                                        .addComponent(_lastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)))
                                .addComponent(_email)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, parent_PanelLayout.createSequentialGroup()
                                    .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(_city, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(_phoneNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(_cityError)
                                        .addComponent(_emailError))
                                    .addGap(95, 95, 95)
                                    .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(parent_PanelLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(parent_PanelLayout.createSequentialGroup()
                                            .addComponent(_stateError)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(_program, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(211, 211, 211))))))
                        .addGap(62, 62, 62))
                    .addGroup(parent_PanelLayout.createSequentialGroup()
                        .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_firstNameError)
                            .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addComponent(_phoneError)
                                .addComponent(_bloodGrouplist, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(datePicker1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, parent_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
        );
        parent_PanelLayout.setVerticalGroup(
            parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parent_PanelLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(parent_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(parent_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(5, 5, 5)
                .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_firstNameError)
                    .addComponent(_lastNameError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(parent_PanelLayout.createSequentialGroup()
                        .addComponent(_email, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(_emailError)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(_city, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_program, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(parent_PanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(63, 63, 63)))
                .addGap(5, 5, 5)
                .addGroup(parent_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_cityError)
                    .addComponent(_stateError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(_phoneError)
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(datePicker1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(_bloodGrouplist, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(Submit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        getContentPane().add(parent_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _phoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__phoneNumberActionPerformed

    }//GEN-LAST:event__phoneNumberActionPerformed

    private void _cityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__cityActionPerformed

    }//GEN-LAST:event__cityActionPerformed

    private void _emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__emailActionPerformed

    }//GEN-LAST:event__emailActionPerformed

    private void _lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__lastNameActionPerformed

    }//GEN-LAST:event__lastNameActionPerformed

    private void _firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__firstNameActionPerformed

    }//GEN-LAST:event__firstNameActionPerformed

    private void Submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit_btnActionPerformed
        if (validateForm()) {
            JOptionPane.showMessageDialog(this, "Form submitted successfully!");
            SubmitDataToDatabase();
        }
        else  JOptionPane.showMessageDialog(null, "Please Enter Valid Data", "Invalid Input", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_Submit_btnActionPerformed

    private void _programActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__programActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event__programActionPerformed

    private boolean validateForm() {
    boolean isValid = true;
    
    // Reset all error labels
    _firstNameError.setText("");
   _lastNameError.setText("");
    _emailError.setText("");
    _cityError.setText("");
    _stateError.setText("");
     _phoneError.setText("");
   

    if (!_firstName.getText().trim().matches("[a-zA-Z]+")) {
        _firstNameError.setText("Invalid First Name");
        isValid = false;
    }
    
    if (!_lastName.getText().trim().matches("[a-zA-Z]+")) {
        _lastNameError.setText("Invalid Last Name");
        isValid = false;
    }

    if (!_email.getText().trim().matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$")) {
        _emailError.setText("Invalid email format");
        isValid = false;
    }
    
    if (!_city.getText().trim().matches("[a-zA-Z]+")) {
        _cityError.setText("Invalid City Name");
        isValid = false;
    }
    
   if (!_phoneNumber.getText().trim().matches("\\d{10}")) { 
    _phoneError.setText("Phone Number must be of 10 digits");
    isValid = false;
    }

    return isValid;
}      
    private void SubmitDataToDatabase()
    {
        try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sys", "root", "prashant123?")) {
        
        //Prepare SQL INSERT statement
        String sql = "INSERT INTO students(roll_number, name, program, birth_date, blood_group, address, mobile_number, email, print_status) " +
                     "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        
        PreparedStatement pstmt = conn.prepareStatement(sql);
        
        //Set parameters for the prepared statement
                
        Random _random = new Random();
        int randNum = _random.nextInt(200);
        int temp = 0;
        while(temp == randNum){
         randNum = _random.nextInt(200);
        }
        temp = randNum;
        pstmt.setInt(1, temp); // roll
        pstmt.setString(2, _firstName.getText() + " " + _lastName.getText()); // name 
        
        String selectedProgram = (String)_program.getSelectedItem();
        pstmt.setString(3,selectedProgram);    // program 
        
        LocalDate selectedDate = datePicker1.getDate();
        if (selectedDate == null) {
            JOptionPane.showMessageDialog(this, "Please select a birth date!", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
        String formattedDate = selectedDate.format(DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        pstmt.setString(4, formattedDate); //birth date
        
        String selectedBlood = (String)_bloodGrouplist.getSelectedItem();
        pstmt.setString(5, selectedBlood);      // blood_group
        pstmt.setString(6, _city.getText());         // address
        pstmt.setString(7, _phoneNumber.getText()); // mobile_number
        pstmt.setString(8, _email.getText());           // email
        pstmt.setBoolean(9, false);                     // print_status
        
        //Execute the insert
        int rowsAffected = pstmt.executeUpdate();
        
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Data saved successfully!");
            
        } else {
            JOptionPane.showMessageDialog(this, "Failed to save data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        //Close resources
        pstmt.close();
        conn.close();
        
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this, "Invalid number format", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetailsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit_btn;
    private javax.swing.JComboBox<String> _bloodGrouplist;
    private javax.swing.JTextField _city;
    private javax.swing.JLabel _cityError;
    private javax.swing.JTextField _email;
    private javax.swing.JLabel _emailError;
    private javax.swing.JTextField _firstName;
    private javax.swing.JLabel _firstNameError;
    private javax.swing.JTextField _lastName;
    private javax.swing.JLabel _lastNameError;
    private javax.swing.JLabel _phoneError;
    private javax.swing.JTextField _phoneNumber;
    private javax.swing.JComboBox<String> _program;
    private javax.swing.JLabel _stateError;
    private javax.swing.JPanel background_Panel;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel parent_Panel;
    // End of variables declaration//GEN-END:variables
}
