/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.idcardgenerator;

import java.util.Map;

/**
 *
 * @author Prashant PC
 */
public class IdCardForm extends javax.swing.JFrame {

    /**
     * Creates new form IdCardForm
     */
    public IdCardForm(Map<String, String> studentData) {
        initComponents();
        
        name.setText(studentData.get("name"));
        roll.setText(studentData.get("roll"));
        program.setText(studentData.get("program"));
        dob.setText(studentData.get("dob"));
        blood.setText(studentData.get("blood"));
        address.setText(studentData.get("address"));
        mobile.setText(studentData.get("mobile"));
        mail.setText(studentData.get("email"));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        roll = new javax.swing.JLabel();
        program = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        blood = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Date of Birth:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 360, 140, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Roll Number:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(40, 300, 120, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Program:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(50, 330, 110, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Blood Group:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(40, 390, 120, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Address :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(50, 420, 110, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mobile :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(50, 450, 110, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Email:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(50, 480, 110, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Name :");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(50, 270, 110, 40);

        name.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name.setText("name");
        jPanel2.add(name);
        name.setBounds(180, 270, 200, 40);

        roll.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        roll.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roll.setText("roll");
        jPanel2.add(roll);
        roll.setBounds(180, 300, 200, 40);

        program.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        program.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        program.setText("program");
        jPanel2.add(program);
        program.setBounds(180, 330, 200, 40);

        address.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        address.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        address.setText("address");
        jPanel2.add(address);
        address.setBounds(180, 420, 200, 40);

        blood.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        blood.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        blood.setText("blood");
        jPanel2.add(blood);
        blood.setBounds(180, 390, 200, 40);

        dob.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        dob.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dob.setText("dob");
        jPanel2.add(dob);
        dob.setBounds(180, 360, 200, 40);

        mail.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        mail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mail.setText("mail");
        jPanel2.add(mail);
        mail.setBounds(180, 480, 200, 40);

        mobile.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        mobile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mobile.setText("mobile");
        jPanel2.add(mobile);
        mobile.setBounds(180, 450, 200, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              // new IdCardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JLabel blood;
    private javax.swing.JLabel dob;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JLabel program;
    private javax.swing.JLabel roll;
    // End of variables declaration//GEN-END:variables
}
