/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.idcardgenerator;

import java.awt.Image;
import java.util.Base64;
import java.util.Map;
import javax.swing.ImageIcon;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.io.image.ImageDataFactory;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Prashant PC
 */
public class IdCardForm extends javax.swing.JFrame {

    /**
     * Creates new form IdCardForm
     */
    public IdCardForm(Map<String, String> studentData) {
        initComponents();
              
        name.setText(studentData.get("name").toUpperCase());
        roll.setText(studentData.get("roll").toUpperCase());
        program.setText(studentData.get("program").toUpperCase());
        dob.setText(studentData.get("dob"));
        blood.setText(studentData.get("blood"));
        address.setText(studentData.get("address").toUpperCase());
        mobile.setText(studentData.get("mobile"));
        mail.setText(studentData.get("email"));
        
        String base64Image =  studentData.get("image");
        try {
            // Convert Base64 back to binary
            byte[] imageBytes = Base64.getDecoder().decode(base64Image);
            ImageIcon icon = new ImageIcon(imageBytes);
            
          java.awt.Image scaledImage = icon.getImage().getScaledInstance(
                profileImage.getWidth(), 
                profileImage.getHeight(), 
                java.awt.Image.SCALE_SMOOTH
            );
           profileImage.setIcon(new ImageIcon(scaledImage));
        } catch (IllegalArgumentException e) {
            System.err.println("Invalid Base64 image data");
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        idCardPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        roll = new javax.swing.JLabel();
        program = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        blood = new javax.swing.JLabel();
        dob = new javax.swing.JLabel();
        mail = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        profileImage = new javax.swing.JLabel();
        IdCardImage = new javax.swing.JLabel();
        exportBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idCardPanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Date of Birth:");
        idCardPanel.add(jLabel2);
        jLabel2.setBounds(20, 360, 140, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Roll Number:");
        idCardPanel.add(jLabel3);
        jLabel3.setBounds(40, 300, 120, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Program:");
        idCardPanel.add(jLabel6);
        jLabel6.setBounds(50, 330, 110, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Blood Group:");
        idCardPanel.add(jLabel7);
        jLabel7.setBounds(40, 390, 120, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Address :");
        idCardPanel.add(jLabel8);
        jLabel8.setBounds(50, 420, 110, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mobile :");
        idCardPanel.add(jLabel9);
        jLabel9.setBounds(50, 450, 110, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Email:");
        idCardPanel.add(jLabel10);
        jLabel10.setBounds(50, 480, 110, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Name :");
        idCardPanel.add(jLabel11);
        jLabel11.setBounds(50, 270, 110, 40);

        name.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        name.setText("name");
        idCardPanel.add(name);
        name.setBounds(180, 270, 200, 40);

        roll.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        roll.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        roll.setText("roll");
        idCardPanel.add(roll);
        roll.setBounds(180, 300, 200, 40);

        program.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        program.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        program.setText("program");
        idCardPanel.add(program);
        program.setBounds(180, 330, 200, 40);

        address.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        address.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        address.setText("address");
        idCardPanel.add(address);
        address.setBounds(180, 420, 200, 40);

        blood.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        blood.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        blood.setText("blood");
        idCardPanel.add(blood);
        blood.setBounds(180, 390, 200, 40);

        dob.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        dob.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dob.setText("dob");
        idCardPanel.add(dob);
        dob.setBounds(180, 360, 200, 40);

        mail.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        mail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mail.setText("mail");
        idCardPanel.add(mail);
        mail.setBounds(180, 480, 200, 40);

        mobile.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        mobile.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mobile.setText("mobile");
        idCardPanel.add(mobile);
        mobile.setBounds(180, 450, 200, 40);
        idCardPanel.add(profileImage);
        profileImage.setBounds(120, 50, 150, 150);

        IdCardImage.setBackground(new java.awt.Color(255, 255, 255));
        IdCardImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IdCardTemplate.jpg"))); // NOI18N
        idCardPanel.add(IdCardImage);
        IdCardImage.setBounds(0, 0, 382, 570);

        exportBtn.setFont(new java.awt.Font("Open Sans SemiBold", 0, 18)); // NOI18N
        exportBtn.setText("Export");
        exportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(idCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void exportToPDF(JPanel panel) {
    // Create file chooser
    JFileChooser fileChooser = new JFileChooser();
    
    // Set default to Desktop
    fileChooser.setCurrentDirectory(new File(System.getProperty("user.home") + File.separator + "Desktop"));
    
    // Configure file chooser
    fileChooser.setDialogTitle("Save ID Card as PDF");
    fileChooser.setFileFilter(new FileNameExtensionFilter("PDF Files", "pdf"));
    fileChooser.setSelectedFile(new File("ID_Card.pdf")); // Default filename
    
    // Show save dialog
    int userSelection = fileChooser.showSaveDialog(panel);
    
    if (userSelection == JFileChooser.APPROVE_OPTION) {
        File fileToSave = fileChooser.getSelectedFile();
        
        // Ensure .pdf extension
        String filePath = fileToSave.getAbsolutePath();
        if (!filePath.toLowerCase().endsWith(".pdf")) {
            filePath += ".pdf";
        }
        
        try {
            // Create PDF writer
            PdfWriter writer = new PdfWriter(filePath);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);
            
            // Convert panel to image
            BufferedImage bufferedImage = new BufferedImage(
                panel.getWidth(),
                panel.getHeight(),
                BufferedImage.TYPE_INT_RGB
            );
            panel.paint(bufferedImage.createGraphics());
            
            // Convert to bytes
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bufferedImage, "PNG", baos);
            
            // Add to PDF
            com.itextpdf.layout.element.Image pdfImage = 
                new com.itextpdf.layout.element.Image(ImageDataFactory.create(baos.toByteArray()));
            
            document.add(pdfImage);
            document.close();
            
            JOptionPane.showMessageDialog(panel, 
                "ID Card saved successfully to:\n" + filePath,
                "Success", 
                JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(panel, 
                "PDF export failed: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
     }
    }
    
    private void exportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportBtnActionPerformed
        exportToPDF(idCardPanel);
    }//GEN-LAST:event_exportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IdCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IdCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IdCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IdCardForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              // new IdCardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdCardImage;
    private javax.swing.JLabel address;
    private javax.swing.JLabel blood;
    private javax.swing.JLabel dob;
    private javax.swing.JButton exportBtn;
    private javax.swing.JPanel idCardPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel mail;
    private javax.swing.JLabel mobile;
    private javax.swing.JLabel name;
    private javax.swing.JLabel profileImage;
    private javax.swing.JLabel program;
    private javax.swing.JLabel roll;
    // End of variables declaration//GEN-END:variables
}
